In [1]:
using DataFrames
using CSV
using Downloads

csvFile = "avocado.csv"

"avocado.csv"

In [2]:
abacatesCsv = CSV.File(csvFile)[1:10,:]

10×1 Matrix{CSV.Row}:
 CSV.Row: (Column1 = 0, Date = Dates.Date("2015-12-27"), AveragePrice = 1.33, Total Volume = 64236.62, 4046 = 1036.74, 4225 = 54454.85, 4770 = 48.16, Total Bags = 8696.87, Small Bags = 8603.62, Large Bags = 93.25, XLarge Bags = 0.0, type = "conventional", year = 2015, region = "Albany")
 CSV.Row: (Column1 = 1, Date = Dates.Date("2015-12-20"), AveragePrice = 1.35, Total Volume = 54876.98, 4046 = 674.28, 4225 = 44638.81, 4770 = 58.33, Total Bags = 9505.56, Small Bags = 9408.07, Large Bags = 97.49, XLarge Bags = 0.0, type = "conventional", year = 2015, region = "Albany")
 CSV.Row: (Column1 = 2, Date = Dates.Date("2015-12-13"), AveragePrice = 0.93, Total Volume = 118220.22, 4046 = 794.7, 4225 = 109149.67, 4770 = 130.5, Total Bags = 8145.35, Small Bags = 8042.21, Large Bags = 103.14, XLarge Bags = 0.0, type = "conventional", year = 2015, region = "Albany")
 CSV.Row: (Column1 = 3, Date = Dates.Date("2015-12-06"), AveragePrice = 1.08, Total Volume = 78992.15, 4046 = 1132

In [7]:
abacatesDataframe = CSV.File(csvFile) |> DataFrame;

In [1]:
?|>

search: |>



```
|>(x, f)
```

Applies a function to the preceding argument. This allows for easy function chaining.

# Examples

```jldoctest
julia> [1:5;] |> x->x.^2 |> sum |> inv
0.01818181818181818
```


In [5]:
read(csvFile, DataFrame; delim="|") # segue outra forma de criar um dataframe à partir de uma matriz CSV.read(path, DataFrame;)

LoadError: MethodError: no method matching read(::String, ::Type{DataFrame}; delim="|")
Closest candidates are:
  read(::AbstractString, ::Type{T}) where T at io.jl:434 got unsupported keyword argument "delim"
  read(::AbstractString, ::Any...) at io.jl:432 got unsupported keyword argument "delim"
  read(::IO, ::Type) at io.jl:967 got unsupported keyword argument "delim"

In [9]:
abacatesDataframe[1:10,:]

10×14 DataFrame
 Row │ Column1  Date        AveragePrice  Total Volume   4046     4225         ⋯
     │ Int64    Date…       Float64       Float64        Float64  Float64      ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │       0  2015-12-27          1.33  64236.6        1036.74  54454.8      ⋯
   2 │       1  2015-12-20          1.35  54877.0         674.28  44638.8
   3 │       2  2015-12-13          0.93      1.1822e5    794.7       1.0915e5
   4 │       3  2015-12-06          1.08  78992.1        1132.0   71976.4
   5 │       4  2015-11-29          1.28  51039.6         941.48  43838.4      ⋯
   6 │       5  2015-11-22          1.26  55979.8        1184.27  48068.0
   7 │       6  2015-11-15          0.99  83453.8        1368.92  73672.7
   8 │       7  2015-11-08          0.98      1.09428e5   703.75      1.01815e
   9 │       8  2015-11-01          1.02  99811.4        1022.15  87315.6      ⋯
  10 │       9  2015-10-25          1.07  74338.8         842.4   64757.4
                                                               9 columns omitted

In [20]:
abacatesDataframe[[1, 5, 10], :]

3×14 DataFrame
 Row │ Column1  Date        AveragePrice  Total Volume  4046     4225     4770 ⋯
     │ Int64    Date…       Float64       Float64       Float64  Float64  Floa ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │       0  2015-12-27          1.33       64236.6  1036.74  54454.8    48 ⋯
   2 │       4  2015-11-29          1.28       51039.6   941.48  43838.4    75
   3 │       9  2015-10-25          1.07       74338.8   842.4   64757.4   113
                                                               8 columns omitted

In [10]:
nrow(abacatesDataframe)

18249

In [ ]:
#ver todas as linhas do dataframe
show(abacatesDataframe, allrows=true)

In [11]:
#ver todas as colunas, até as que nao cabem na tela
show(abacatesDataframe, allcols=true)

18249×14 DataFrame
   Row │ Column1  Date        AveragePrice  Total Volume   4046      4225           4770     Total Bags     Small Bags     Large Bags  XLarge Bags  type          year   region           
       │ Int64    Date…       Float64       Float64        Float64   Float64        Float64  Float64        Float64        Float64     Float64      String        Int64  String           
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
     1 │       0  2015-12-27          1.33  64236.6         1036.74  54454.8          48.16   8696.87        8603.62            93.25         0.0   conventional   2015  Albany
     2 │       1  2015-12-20          1.35  54877.0          674.28  44638.8          58.33   9505.56        9408.07            97.49         0.0   conventional   2015  Albany
     3 │       2  2015-12-13          0.93      1.1822e5     794.7  

In [12]:
eltype.(eachcol(abacatesDataframe))

14-element Vector{DataType}:
 Int64
 Dates.Date
 Float64
 Float64
 Float64
 Float64
 Float64
 Float64
 Float64
 Float64
 Float64
 String
 Int64
 String

In [13]:
#10 ultimas
last(abacatesDataframe, 10)

10×14 DataFrame
 Row │ Column1  Date        AveragePrice  Total Volume  4046     4225     4770 ⋯
     │ Int64    Date…       Float64       Float64       Float64  Float64  Floa ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │       2  2018-03-11          1.56       22128.4  2162.67  3194.25     8 ⋯
   2 │       3  2018-03-04          1.54       17393.3  1832.24  1905.57     0
   3 │       4  2018-02-25          1.57       18421.2  1974.26  2482.65     0
   4 │       5  2018-02-18          1.56       17597.1  1892.05  1928.36     0
   5 │       6  2018-02-11          1.57       15986.2  1924.28  1368.32     0 ⋯
   6 │       7  2018-02-04          1.63       17074.8  2046.96  1529.2      0
   7 │       8  2018-01-28          1.71       13888.0  1191.7   3431.5      0
   8 │       9  2018-01-21          1.87       13766.8  1191.92  2452.79   727
   9 │      10  2018-01-14          1.93       16205.2  1527.63  2981.04   727 ⋯
  10 │      11  2018-01-07          1.62       17489.6  2894.77  2356.13   224
                                                               8 columns omitted

In [14]:
#10 primeras
first(abacatesDataframe, 10)

10×14 DataFrame
 Row │ Column1  Date        AveragePrice  Total Volume   4046     4225         ⋯
     │ Int64    Date…       Float64       Float64        Float64  Float64      ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │       0  2015-12-27          1.33  64236.6        1036.74  54454.8      ⋯
   2 │       1  2015-12-20          1.35  54877.0         674.28  44638.8
   3 │       2  2015-12-13          0.93      1.1822e5    794.7       1.0915e5
   4 │       3  2015-12-06          1.08  78992.1        1132.0   71976.4
   5 │       4  2015-11-29          1.28  51039.6         941.48  43838.4      ⋯
   6 │       5  2015-11-22          1.26  55979.8        1184.27  48068.0
   7 │       6  2015-11-15          0.99  83453.8        1368.92  73672.7
   8 │       7  2015-11-08          0.98      1.09428e5   703.75      1.01815e
   9 │       8  2015-11-01          1.02  99811.4        1022.15  87315.6      ⋯
  10 │       9  2015-10-25          1.07  74338.8         842.4   64757.4
                                                               9 columns omitted

In [21]:
abacatesDataframe.AveragePrice

18249-element Vector{Float64}:
 1.33
 1.35
 0.93
 1.08
 1.28
 1.26
 0.99
 0.98
 1.02
 1.07
 1.12
 1.28
 1.31
 ⋮
 1.62
 1.56
 1.56
 1.54
 1.57
 1.56
 1.57
 1.63
 1.71
 1.87
 1.93
 1.62

In [23]:
abacatesDataframe[:,[:AveragePrice]]

18249×1 DataFrame
   Row │ AveragePrice 
       │ Float64      
───────┼──────────────
     1 │         1.33
     2 │         1.35
     3 │         0.93
     4 │         1.08
     5 │         1.28
     6 │         1.26
     7 │         0.99
     8 │         0.98
     9 │         1.02
    10 │         1.07
    11 │         1.12
   ⋮   │      ⋮
 18240 │         1.56
 18241 │         1.54
 18242 │         1.57
 18243 │         1.56
 18244 │         1.57
 18245 │         1.63
 18246 │         1.71
 18247 │         1.87
 18248 │         1.93
 18249 │         1.62
    18228 rows omitted

In [22]:
abacatesDataframe.AveragePrice[10: 20, :]

11×1 Matrix{Float64}:
 1.07
 1.12
 1.28
 1.31
 0.99
 1.33
 1.28
 1.11
 1.07
 1.34
 1.33

In [8]:
abacatesDataframe[10:20,[:AveragePrice]]

11×1 DataFrame
 Row │ AveragePrice 
     │ Float64      
─────┼──────────────
   1 │         1.07
   2 │         1.12
   3 │         1.28
   4 │         1.31
   5 │         0.99
   6 │         1.33
   7 │         1.28
   8 │         1.11
   9 │         1.07
  10 │         1.34
  11 │         1.33

In [25]:
CsvSemData = select(abacatesDataframe, Not(:Date)) 

18249×13 DataFrame
   Row │ Column1  AveragePrice  Total Volume   4046      4225           4770   ⋯
       │ Int64    Float64       Float64        Float64   Float64        Float6 ⋯
───────┼────────────────────────────────────────────────────────────────────────
     1 │       0          1.33  64236.6         1036.74  54454.8          48.1 ⋯
     2 │       1          1.35  54877.0          674.28  44638.8          58.3
     3 │       2          0.93      1.1822e5     794.7       1.0915e5    130.5
     4 │       3          1.08  78992.1         1132.0   71976.4          72.5
     5 │       4          1.28  51039.6          941.48  43838.4          75.7 ⋯
     6 │       5          1.26  55979.8         1184.27  48068.0          43.6
     7 │       6          0.99  83453.8         1368.92  73672.7          93.2
     8 │       7          0.98      1.09428e5    703.75      1.01815e5    80.0
     9 │       8          1.02  99811.4         1022.15  87315.6          85.3 ⋯
    10 │       9          1.07  74338.8          842.4   64757.4         113.0
    11 │      10          1.12  84843.4          924.86  75595.9         117.0
   ⋮   │    ⋮          ⋮              ⋮           ⋮            ⋮           ⋮   ⋱
 18240 │       2          1.56  22128.4         2162.67   3194.25          8.9
 18241 │       3          1.54  17393.3         1832.24   1905.57          0.0 ⋯
 18242 │       4          1.57  18421.2         1974.26   2482.65          0.0
 18243 │       5          1.56  17597.1         1892.05   1928.36          0.0
 18244 │       6          1.57  15986.2         1924.28   1368.32          0.0
 18245 │       7          1.63  17074.8         2046.96   1529.2           0.0 ⋯
 18246 │       8          1.71  13888.0         1191.7    3431.5           0.0
 18247 │       9          1.87  13766.8         1191.92   2452.79        727.9
 18248 │      10          1.93  16205.2         1527.63   2981.04        727.0
 18249 │      11          1.62  17489.6         2894.77   2356.13        224.5 ⋯
                                                8 columns and 18228 rows omitted

In [26]:
select(abacatesDataframe, r"X")[1:4,:]

4×1 DataFrame
 Row │ XLarge Bags 
     │ Float64     
─────┼─────────────
   1 │         0.0
   2 │         0.0
   3 │         0.0
   4 │         0.0

In [27]:
select(abacatesDataframe, :Date => :Valdir)[1:4,:]

4×1 DataFrame
 Row │ Valdir     
     │ Date…      
─────┼────────────
   1 │ 2015-12-27
   2 │ 2015-12-20
   3 │ 2015-12-13
   4 │ 2015-12-06

In [28]:
select(abacatesDataframe, :AveragePrice)[1:5,:] #outra maneira para se acessar uma coluna
select(abacatesDataframe, :AveragePrice, :AveragePrice => ByRow(sqrt))[1:5,:]

5×2 DataFrame
 Row │ AveragePrice  AveragePrice_sqrt 
     │ Float64       Float64           
─────┼─────────────────────────────────
   1 │         1.33           1.15326
   2 │         1.35           1.1619
   3 │         0.93           0.964365
   4 │         1.08           1.03923
   5 │         1.28           1.13137

In [2]:
people = DataFrame(ID = [20, 40], Name = ["John Doe", "Jane Doe"])

2×2 DataFrame
 Row │ ID     Name     
     │ Int64  String   
─────┼─────────────────
   1 │    20  John Doe
   2 │    40  Jane Doe

In [4]:
jobs = DataFrame(ID = [20, 60], Job = ["Lawyer", "Astronaut"])

2×2 DataFrame
 Row │ ID     Job       
     │ Int64  String    
─────┼──────────────────
   1 │    20  Lawyer
   2 │    60  Astronaut

In [5]:
innerjoin(people, jobs, on=:ID)

1×3 DataFrame
 Row │ ID     Name      Job    
     │ Int64  String    String 
─────┼─────────────────────────
   1 │    20  John Doe  Lawyer

In [6]:
leftjoin(people, jobs, on = :ID)

2×3 DataFrame
 Row │ ID     Name      Job     
     │ Int64  String    String? 
─────┼──────────────────────────
   1 │    20  John Doe  Lawyer
   2 │    40  Jane Doe  missing 

In [ ]:
rigth join 

Retorna os valores da tabela à direita, independentemente se existam registros na tabela à esquerda 

In [35]:
rightjoin(people, jobs, on = :ID)

2×3 DataFrame
 Row │ ID     Name      Job       
     │ Int64  String?   String    
─────┼────────────────────────────
   1 │    20  John Doe  Lawyer
   2 │    60  missing   Astronaut

In [7]:
outerjoin(people, jobs, on = :ID)

3×3 DataFrame
 Row │ ID     Name      Job       
     │ Int64  String?   String?   
─────┼────────────────────────────
   1 │    20  John Doe  Lawyer
   2 │    40  Jane Doe  missing   
   3 │    60  missing   Astronaut

In [37]:
semijoin(people, jobs, on = :ID)

1×2 DataFrame
 Row │ ID     Name     
     │ Int64  String   
─────┼─────────────────
   1 │    20  John Doe

In [38]:
antijoin(people, jobs, on = :ID)

1×2 DataFrame
 Row │ ID     Name     
     │ Int64  String   
─────┼─────────────────
   1 │    40  Jane Doe

In [39]:
crossjoin(people, jobs, makeunique = true)

4×4 DataFrame
 Row │ ID     Name      ID_1   Job       
     │ Int64  String    Int64  String    
─────┼───────────────────────────────────
   1 │    20  John Doe     20  Lawyer
   2 │    20  John Doe     60  Astronaut
   3 │    40  Jane Doe     20  Lawyer
   4 │    40  Jane Doe     60  Astronaut